### ISSUE TITLE
Chemical Plant elements

### ISSUE THREAD

**Issue by erwanp** [abhishekvraman/py-and-id#2]
Hello, nice package (and nice description!)

Your last commits include Pumps and check valves. ==> Is there an example Jupyter Notebook showing how to use them ? 

It would be of great interest for us for the Python monitoring of our plasmalyser pilot plant @pag1pag @jakeon11

**Comment by abhishekvraman** [comment]
Hi @erwanp ,
Thank you for showing interest! Did not expect industry experts are looking into it. 
The package is a modification of schmedraw which is used to create electric circuits. 
py-and-id is work progress and has only 2 elements. 
[The only example is here from cell 5 and 6.](https://github.com/abhishekvraman/py-and-id/blob/3e700b483d1812ddcf3083970ff27b0142590b66/tests/notebooks/test_backend.ipynb)

If you want a developed flowsheeting package I recommend to use https://github.com/Nukleon84/pyflowsheet.

Just for my curiosity, what king of monitoring you are doing in your pilot plant?

**Comment by erwanp** [comment]
Thanks for the recommandation. 
We're monitoring Plasma generators; Mass flow meters; Temperature sensors; Pressure sensors; Heat Exchangers; Pumps

**Comment by abhishekvraman** [comment]
I am also working on another project which a python package to analyze chemical plants. You can import flow meters and pumps and attach them.
https://github.com/abhishekvraman/Propylean

Here are some notebooks: https://github.com/abhishekvraman/Propylean/tree/main/Models

I am not sure it would be useful to you but if you can give me some feedback then I can improve it for your use case.

**Comment by erwanp** [comment]
Thanks, forwarding to the team
